version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

#  migration:
#    build: .
#    command: python manage.py migrate --noinput
#    volumes:
#      - .:/code
#    depends_on:
#      - db

#version: '2'
#services:
#  web:
#    build: .
#    ports:
#      - "5000:5000"
#    env_file: .env
#    depends_on:
#      - db
#    volumes:
#      - ./webapp:/opt/webapp
#  db:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
