# Generated by Django 3.1.1 on 2020-09-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200911_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer', verbose_name='pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='core.cart', verbose_name='carrinho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cart', to='core.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'inclusão',
                'verbose_name_plural': 'inclusões',
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('status', models.CharField(choices=[('PNDT', 'Pendente'), ('SHPD', 'Despachado'), ('DLVD', 'Entregue')], default='PNDT', max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.order', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='core.product', verbose_name='produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='content',
            field=models.ManyToManyField(blank=True, through='core.ProductCart', to='core.Product'),
        ),
    ]
