# Generated by Django 3.1.1 on 2020-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200911_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PNDT', 'Pendente'), ('SHPD', 'Despachado'), ('DLVD', 'Entregue')], default='PNDT', max_length=4),
        ),
    ]
