# Generated by Django 3.1.1 on 2020-09-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200911_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('TO_BE_SHIPPED', 'Pendente'), ('SHIPPED', 'Despachado'), ('DELIVERED', 'Entregue')], default='TO_BE_SHIPPED', max_length=15),
        ),
    ]
