# Generated by Django 3.1.1 on 2020-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200912_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('TO_BE_SHIPPED', 'Pendente'), ('SHIPPED', 'Despachado'), ('DELIVERED', 'Entregue')], default='TO_BE_SHIPPED', max_length=15),
        ),
    ]
