# Generated by Django 3.1.1 on 2020-09-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPENED', 'Aberto'), ('TO_BE_SHIPPED', 'Pendente'), ('SHIPPED', 'Despachado'), ('DELIVERED', 'Entregue')], default='OPENED', max_length=15),
        ),
    ]
