# Generated by Django 3.1.1 on 2020-09-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200912_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='OrderItem',
        ),
    ]
