# Generated by Django 3.1.1 on 2020-09-27 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200925_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='content',
            new_name='products',
        ),
    ]
