# Generated by Django 3.1.1 on 2020-09-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
    ]
