# Generated by Django 3.1.1 on 2020-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200929_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_checkout_opened_orders', 'Can checkout opened orders'), ('can_dispatch_pending_orders', 'Can dispatch pending orders')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
