# Generated by Django 3.1.1 on 2020-09-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_nomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_manage_product', 'Can manage product'),), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
