# Generated by Django 3.1.1 on 2020-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200930_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPENED', 'Aberto'), ('TO_BE_SHIPPED', 'Pendente'), ('SHIPPED', 'Despachado')], default='OPENED', max_length=15),
        ),
    ]
