# Generated by Django 3.1.1 on 2020-10-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201001_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoModel',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('can_checkout_opened_orders', 'Can checkout opened orders'), ('can_dispatch_pending_orders', 'Can dispatch pending orders')), 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
