# Generated by Django 3.1.1 on 2020-10-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201002_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
    ]
